import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import type { IntakeAnswers, PhotoAsset } from "@/lib/types";

export const runtime = "nodejs";

function slugify(s: string) {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "site"
  );
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as {
      html: string;
      intake: IntakeAnswers;
    };

    if (!body?.html) {
      return NextResponse.json({ error: "html required" }, { status: 400 });
    }

    const slug = slugify(body.intake?.businessName || "site");
    const zip = new JSZip();

    zip.file("index.html", body.html);

    // Include photos if any
    if (body.intake?.photos?.length) {
      const photosDir = zip.folder("assets");
      for (const p of body.intake.photos as PhotoAsset[]) {
        const match = p.dataUrl.match(/^data:(.*?);base64,(.*)$/);
        if (!match) continue;
        const [, , b64] = match;
        const safeName = p.name.replace(/[^\w.\-]/g, "_");
        photosDir?.file(safeName, b64, { base64: true });
      }
    }

    zip.file(
      "README.md",
      `# ${body.intake?.businessName || "Site"}

Generated by agent-site-builder.

## Files
- \`index.html\` — the full page. Open it in a browser, upload to any static host, or drop it onto Railway / Netlify / GitHub Pages / Cloudflare Pages.
- \`assets/\` — any photos you uploaded during intake.

## Deploy

### Railway (static site)
1. \`railway init\` in this directory
2. \`railway up\`

### GitHub Pages
1. Create a repo and push these files to it.
2. Settings → Pages → source: branch \`main\`, folder \`/\`.

### Netlify / Vercel / Cloudflare
Drag this folder into the upload box.
`
    );

    const buf = await zip.generateAsync({ type: "blob" });

    return new Response(buf as Blob, {
      headers: {
        "content-type": "application/zip",
        "content-disposition": `attachment; filename="${slug}.zip"`,
      },
    });
  } catch (err: any) {
    console.error("export error", err);
    return NextResponse.json(
      { error: err?.message || "export failed" },
      { status: 500 }
    );
  }
}
